"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'
import { configureBoneyard } from 'boneyard-js/react'

import _panel_dashboard from './panel-dashboard.bones.json'
import _blackjack_predictor from './blackjack-predictor.bones.json'
import _crash_predictor from './crash-predictor.bones.json'
import _mines_predictor from './mines-predictor.bones.json'
import _moles_predictor from './moles-predictor.bones.json'

configureBoneyard({"color":"#e5e5e5","darkColor":"#1a1a1a","animate":"shimmer","shimmerColor":"#ebebeb","darkShimmerColor":"#2a2a2a"})

registerBones({
  "panel-dashboard": _panel_dashboard,
  "blackjack-predictor": _blackjack_predictor,
  "crash-predictor": _crash_predictor,
  "mines-predictor": _mines_predictor,
  "moles-predictor": _moles_predictor,
})
