/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WebServicesRouteImport } from './routes/web-services'
import { Route as StakeToolsRouteImport } from './routes/stake-tools'
import { Route as PanelRouteImport } from './routes/panel'
import { Route as MolesRouteImport } from './routes/moles'
import { Route as MinesRouteImport } from './routes/mines'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CustomRouteImport } from './routes/custom'
import { Route as CrashRouteImport } from './routes/crash'
import { Route as BlackjackRouteImport } from './routes/blackjack'
import { Route as IndexRouteImport } from './routes/index'

const WebServicesRoute = WebServicesRouteImport.update({
  id: '/web-services',
  path: '/web-services',
  getParentRoute: () => rootRouteImport,
} as any)
const StakeToolsRoute = StakeToolsRouteImport.update({
  id: '/stake-tools',
  path: '/stake-tools',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelRoute = PanelRouteImport.update({
  id: '/panel',
  path: '/panel',
  getParentRoute: () => rootRouteImport,
} as any)
const MolesRoute = MolesRouteImport.update({
  id: '/moles',
  path: '/moles',
  getParentRoute: () => rootRouteImport,
} as any)
const MinesRoute = MinesRouteImport.update({
  id: '/mines',
  path: '/mines',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomRoute = CustomRouteImport.update({
  id: '/custom',
  path: '/custom',
  getParentRoute: () => rootRouteImport,
} as any)
const CrashRoute = CrashRouteImport.update({
  id: '/crash',
  path: '/crash',
  getParentRoute: () => rootRouteImport,
} as any)
const BlackjackRoute = BlackjackRouteImport.update({
  id: '/blackjack',
  path: '/blackjack',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blackjack': typeof BlackjackRoute
  '/crash': typeof CrashRoute
  '/custom': typeof CustomRoute
  '/login': typeof LoginRoute
  '/mines': typeof MinesRoute
  '/moles': typeof MolesRoute
  '/panel': typeof PanelRoute
  '/stake-tools': typeof StakeToolsRoute
  '/web-services': typeof WebServicesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blackjack': typeof BlackjackRoute
  '/crash': typeof CrashRoute
  '/custom': typeof CustomRoute
  '/login': typeof LoginRoute
  '/mines': typeof MinesRoute
  '/moles': typeof MolesRoute
  '/panel': typeof PanelRoute
  '/stake-tools': typeof StakeToolsRoute
  '/web-services': typeof WebServicesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blackjack': typeof BlackjackRoute
  '/crash': typeof CrashRoute
  '/custom': typeof CustomRoute
  '/login': typeof LoginRoute
  '/mines': typeof MinesRoute
  '/moles': typeof MolesRoute
  '/panel': typeof PanelRoute
  '/stake-tools': typeof StakeToolsRoute
  '/web-services': typeof WebServicesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blackjack'
    | '/crash'
    | '/custom'
    | '/login'
    | '/mines'
    | '/moles'
    | '/panel'
    | '/stake-tools'
    | '/web-services'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blackjack'
    | '/crash'
    | '/custom'
    | '/login'
    | '/mines'
    | '/moles'
    | '/panel'
    | '/stake-tools'
    | '/web-services'
  id:
    | '__root__'
    | '/'
    | '/blackjack'
    | '/crash'
    | '/custom'
    | '/login'
    | '/mines'
    | '/moles'
    | '/panel'
    | '/stake-tools'
    | '/web-services'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlackjackRoute: typeof BlackjackRoute
  CrashRoute: typeof CrashRoute
  CustomRoute: typeof CustomRoute
  LoginRoute: typeof LoginRoute
  MinesRoute: typeof MinesRoute
  MolesRoute: typeof MolesRoute
  PanelRoute: typeof PanelRoute
  StakeToolsRoute: typeof StakeToolsRoute
  WebServicesRoute: typeof WebServicesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/web-services': {
      id: '/web-services'
      path: '/web-services'
      fullPath: '/web-services'
      preLoaderRoute: typeof WebServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stake-tools': {
      id: '/stake-tools'
      path: '/stake-tools'
      fullPath: '/stake-tools'
      preLoaderRoute: typeof StakeToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panel': {
      id: '/panel'
      path: '/panel'
      fullPath: '/panel'
      preLoaderRoute: typeof PanelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moles': {
      id: '/moles'
      path: '/moles'
      fullPath: '/moles'
      preLoaderRoute: typeof MolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mines': {
      id: '/mines'
      path: '/mines'
      fullPath: '/mines'
      preLoaderRoute: typeof MinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom': {
      id: '/custom'
      path: '/custom'
      fullPath: '/custom'
      preLoaderRoute: typeof CustomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crash': {
      id: '/crash'
      path: '/crash'
      fullPath: '/crash'
      preLoaderRoute: typeof CrashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blackjack': {
      id: '/blackjack'
      path: '/blackjack'
      fullPath: '/blackjack'
      preLoaderRoute: typeof BlackjackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlackjackRoute: BlackjackRoute,
  CrashRoute: CrashRoute,
  CustomRoute: CustomRoute,
  LoginRoute: LoginRoute,
  MinesRoute: MinesRoute,
  MolesRoute: MolesRoute,
  PanelRoute: PanelRoute,
  StakeToolsRoute: StakeToolsRoute,
  WebServicesRoute: WebServicesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
